@startuml
'https://plantuml.com/sequence-diagram

start
:Check if number < 0?;
if (yes) then (true)
  :Throw IllegalArgumentException;
else (no)
  :Check if number <= 1?;
  if (yes) then (true)
    :Return number;
  else (no)
    :Return fibonacci(number - 1) + fibonacci(number - 2);
  endif
 endif
stop
@enduml